CREATE DATABASE TO_DO_LIST_DB;
USE TO_DO_LIST_DB;

CREATE TABLE USERS (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE TASKS (
  ID_USERS INT NOT NULL,
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TASK VARCHAR(100),
  STATUS VARCHAR(100)
);

ALTER TABLE TASKS ADD CONSTRAINT FK_TASKS_USERS FOREIGN KEY(ID_USERS) REFERENCES USERS(ID);
